[workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[dependencies]
python = "3.11.*"
appose = ">=0.7.2"
numpy = ">=1.24.0,<2.0"
pandas = ">=2.0"
scipy = ">=1.10"
scikit-learn = ">=1.5"
igraph = ">=0.11"
leidenalg = ">=0.10"
umap-learn = ">=0.5.5"
numba = ">=0.59"
matplotlib-base = ">=3.7"

[pypi-dependencies]
scanpy = ">=1.10"
anndata = ">=0.10"
seaborn = ">=0.13"
squidpy = ">=1.4.0"
harmonypy = ">=0.0.9"
